package dao;
// Generated 22 mai 2024 09:50:59 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Demande generated by hbm2java
 */
@Entity
@Table(name="demande"
    ,catalog="emploi"
)
public class Demande  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private Date date;
     private String ville;
     private Date deplomeDate;

    public Demande() {
    }

    public Demande(String nom, Date date, String ville, Date deplomeDate) {
       this.nom = nom;
       this.date = date;
       this.ville = ville;
       this.deplomeDate = deplomeDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nom", nullable=false, length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", nullable=false, length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="ville", nullable=false, length=45)
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="deplomeDate", nullable=false, length=10)
    public Date getDeplomeDate() {
        return this.deplomeDate;
    }
    
    public void setDeplomeDate(Date deplomeDate) {
        this.deplomeDate = deplomeDate;
    }




}


